CREATE TABLE PROFIT_Q4 AS
SELECT 
    RETAILSALESFACTTABLE.STOREKEY,
    STORE_DIMENSION.STORENAME,
    RETAILSALESFACTTABLE.PRODUCTKEY,
    PRODUCT_DIMENSION.PRODUCT_DESCRIPTION,
    SUM(RETAILSALESFACTTABLE.QUANTITY * PRODUCT_DIMENSION.PRODUCT_PRICE 
        - RETAILSALESFACTTABLE.QUANTITY * PRODUCT_DIMENSION.PRODUCT_COST) AS PROFIT
FROM RETAILSALESFACTTABLE
INNER JOIN STORE_DIMENSION ON STORE_DIMENSION.STOREKEY = RETAILSALESFACTTABLE.STOREKEY
INNER JOIN PRODUCT_DIMENSION ON PRODUCT_DIMENSION.PRODUCT_KEY = RETAILSALESFACTTABLE.PRODUCTKEY
WHERE TRANSACTIONDATE BETWEEN TO_DATE('2025-10-01','YYYY-MM-DD') AND TO_DATE('2025-12-31','YYYY-MM-DD')
GROUP BY RETAILSALESFACTTABLE.STOREKEY, RETAILSALESFACTTABLE.PRODUCTKEY, 
         PRODUCT_DIMENSION.PRODUCT_DESCRIPTION, STORE_DIMENSION.STORENAME
ORDER BY PROFIT ASC